spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 6   #6秒不发送心跳检查，就删除该实例，默认90秒
    lease-renewal-interval-in-seconds: 2  #心跳检查的时间，默认30秒
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
