#server:
  #port: 8662

#spring:
  #application:
    #name: base-patent-plugins
  #data:
    #mongodb:
    #  host: 120.76.190.232
    #  port: 27017
    #  username: root
    #  password: 123456
    #  database: zlbm
    #  authentication-database: admin
    #  repositories:
     #     enabled: true
#eureka:
#  instance:
#    hostname: ${spring.cloud.client.ip-address}
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://120.76.189.9:8761/eureka/