spring:
  application:
    name: base-file-plugins
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/foobar
  rabbitmq:
    host: 192.168.93.129
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1.0    #定义抽样比率，默认为0.1
#  zipkin:
#    enabled: true
#    base-url: http://127.0.0.1:9411/

server:
  port: 8663

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
